# Generated by Django 5.1.6 on 2025-03-01 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_review_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='description',
            new_name='comment',
        ),
    ]
